import json
import logging
from http import HTTPStatus
from typing import Any, Dict

import azure.functions as func


def main(req: func.HttpRequest) -> func.HttpResponse:
    """Handle RingCentral telephony webhooks.

    The handler accepts POSTed JSON payloads from RingCentral (for example,
    call events generated by the RingCentral Embeddable widget) and returns a
    simple acknowledgement so Halo PSA can register the delivery.
    """

    try:
        payload = req.get_json()
    except ValueError:
        logging.warning("RingCentral incoming-call received invalid JSON")
        return func.HttpResponse("Invalid JSON payload", status_code=HTTPStatus.BAD_REQUEST)

    if not isinstance(payload, dict):
        return func.HttpResponse("Request body must be a JSON object", status_code=HTTPStatus.BAD_REQUEST)

    call_type = _as_string(payload.get("type"), default="unknown")
    session_id = _as_string(payload.get("sessionId"), default="")
    direction = _as_string(payload.get("direction"), default="")
    from_number = _extract_number(payload.get("from"))
    to_number = _extract_number(payload.get("to"))

    logging.info(
        "RingCentral call event: type=%s session=%s direction=%s from=%s to=%s",
        call_type,
        session_id,
        direction,
        from_number,
        to_number,
    )

    response_body: Dict[str, Any] = {
        "status": "received",
        "type": call_type,
        "sessionId": session_id,
    }

    return func.HttpResponse(
        json.dumps(response_body),
        status_code=HTTPStatus.OK,
        mimetype="application/json",
    )


def _as_string(value: Any, default: str = "") -> str:
    return value if isinstance(value, str) else default


def _extract_number(value: Any) -> str:
    if isinstance(value, dict) and isinstance(value.get("phoneNumber"), str):
        return value["phoneNumber"]
    if isinstance(value, str):
        return value
    return ""
